language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yurytrafimovich/docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true yurytrafimovich/docker-ci npm run test