Resources:
  DeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Users:
        - !Ref 'DeploymentUser'
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:Describe*
              - cloudformation:List*
              - cloudformation:UpdateStack
              - cloudformation:PreviewStackUpdate
              - cloudformation:ValidateTemplate
              - cloudformation:Get*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - iam:PassRole
              - iam:GetRole
              - iam:CreateRole
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:DeleteRole
              - iam:AttachRolePolicy
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - ec2:*
            Resource:
              - '*'

  DeploymentUser:
    Type: AWS::IAM::User
